### ISSUE TITLE
Move CCF ranks to Conferences

### ISSUE THREAD

**Issue by shaido987** [TatsuyaD7/Time-Series-Work-Conference#10]
Hi,

Thanks for a great work.  
I just made a PR with some minor issues I noticed #9, but there was a larger change I thought of.

Currently, the CCF ranks of the conferences are written for each publication which seems unnecessary. Instead, I think you can just move this information to be under the "Conferences" title. In this way, the information regarding the ranks of the conferences (i.e., what the ranks are, conference average quality, etc.) could also be moved to "Conferences".

**Comment by shaido987** [comment]
I can open a PR with the change to make it clearer if you think it's worthwhile. 😉

**Comment by lixus7** [comment]
Sorry for the late reply. Indeed, as you said, CCF ranks are unnecessary to be mentioned in the publication part. Thanks for your advice and contributions, you can open a PR for those changes as you mentioned in #10. 😉

**Comment by shaido987** [comment]
No problems at all~ Perfect, I will try to submit a PR for it tomorrow.
