### ISSUE TITLE
I want to ask how the stgnn model works

### ISSUE THREAD

**Issue by hxy20172708** [TatsuyaD7/Time-Series-Work-Conference#17]
I want to ask how the stgnn model works

**Comment by lixus7** [comment]
?

**Comment by hxy20172708** [comment]
Traffic Flow Prediction via Spatial Temporal Graph Neural
Network

**Comment by lixus7** [comment]
You could ask Lmissher about his implemention and the url is "https://github.com/LMissher/STGNN".
