### ISSUE TITLE
code link update

### ISSUE THREAD

**Issue by 943fansi** [TatsuyaD7/Time-Series-Work-Conference#18]
1. [Multi-Granularity Residual Learning with Confidence Estimation for Time Series Prediction](https://doi.org/10.1145/3485447.3512056) The code repository for this paper was deleted；
2. [EXIT: Extrapolation and Interpolation-based Neural Controlled Differential Equations for Time-series Classification and Forecasting](https://doi.org/10.1145/3485447.3512030)
code [https://github.com/sheoyon-jhin/EXIT](https://github.com/sheoyon-jhin/EXIT)
3. Paper name of `CAMul` is wrong. [CAMul	EXIT: Extrapolation and Interpolation-based Neural Controlled Differential Equations for Time-series Classification and Forecasting]
4. [RETE: Retrieval-Enhanced Temporal Event Forecasting on Unified Query Product Evolutionary Graph](https://dl.acm.org/doi/pdf/10.1145/3485447.3511974)
code [https://github.com/DiMarzioBian/RETE_TheWebConf](https://github.com/DiMarzioBian/RETE_TheWebConf)
5. [TLogic: Temporal Logical Rules for Explainable Link Forecasting on Temporal Knowledge Graphs](https://arxiv.org/abs/2112.08025)
code [https://github.com/liu-yushan/TLogic](https://github.com/liu-yushan/TLogic)
6. [Long Horizon Forecasting With Temporal Point Processes](https://arxiv.org/pdf/2101.02815.pdf)
code [https://github.com/pratham16cse/DualTPP](https://github.com/pratham16cse/DualTPP)
7. [Time-Series Event Prediction with Evolutionary State Graph](https://arxiv.org/pdf/1905.05006.pdf)
code [https://github.com/VachelHU/EvoNet](https://github.com/VachelHU/EvoNet)
8. [Dynamic Gaussian Mixture Based Deep Generative Model for Robust Forecasting on Sparse Multivariate Time Series](https://arxiv.org/abs/2103.02164)
code [https://github.com/thuwuyinjun/DGM2](https://github.com/thuwuyinjun/DGM2)
9. [Spatio-Temporal Recurrent Networks for Event-Based Optical Flow Estimation](https://arxiv.org/abs/2109.04871)
code [https://github.com/ruizhao26/STE-FlowNet](https://github.com/ruizhao26/STE-FlowNet)

**Comment by lixus7** [comment]
Thanks for your support, i have updated these codes. However, `TLogic`, `DualTPP` and `STE-FlowNet` had not been added because their tasks (Link forecasting, temporal point process and optical flow estimation) were not included.
