### ISSUE TITLE
paper recommendation

### ISSUE THREAD

**Issue by GRAPH-0** [TatsuyaD7/Time-Series-Work-Conference#23]
Hi @lixus7

Thanks for your excellent repo!
Would you mind considering our paper published on ICDE 2023 about diffusion-based imputation models for spatiotemporal time series?
Title: PriSTI: A Conditional Diffusion Framework for Spatiotemporal Imputation
Paper Link: https://arxiv.org/abs/2302.09746
Code Link: https://github.com/LMZZML/PriSTI

**Comment by lixus7** [comment]
Thanks. Congratulations on your great work about time-series imputation.
You can pull request if you don't mind as you could be one visible contributor. 
Of course, I'd be happy to help if you'd like me to add PriSTI. Please let me know.

**Comment by GRAPH-0** [comment]
I have made a pull request for it. Thank you!
