### ISSUE TITLE
BJTaxi数据集就是TaxiBJ哦，可以合并一下

### ISSUE THREAD

**Issue by ByskyXie** [TatsuyaD7/Time-Series-Work-Conference#25]
例如方法ST-SSL中所说的BJTaxi数据集就是TaxiBJ

**Comment by ByskyXie** [comment]
还有“Frigate: Frugal Spatio-temporal Forecasting on Road Networks”这篇的url放错了，放成上一个方法的url了

**Comment by lixus7** [comment]
谢谢更新。
-数据集不止BJTaxi有名字不统一的问题，还有一些其他的也存在着同一个数据但是在不同的文章里叫法不一样的问题。后续时间充裕点再统一去处理下。
-Frigate已更新，谢谢提醒！
